cluster.name: "docker-cluster"
network.host: 0.0.0.0
node.name: elasticsearch
cluster.initial_master_nodes:
  - elasticsearch

# set to 1 to allow single node clusters
# Details: https://github.com/elastic/elasticsearch/pull/17288
discovery.zen.minimum_master_nodes: 1
